### ISSUE TITLE
It isnt working

### ISSUE THREAD

**Issue by Raphty** [EsmailELBoBDev2/Whatismyip#1]
![Screenshot 2019-07-25 at 2 25 00 PM](https://user-images.githubusercontent.com/11504285/61874248-6cea3200-aed7-11e9-87b8-0e01e94288d9.png)

I am using 
MacOS 10.14
FF 68.0.1

and I am using µMatrix but it doesn't appear to block anything

**Comment by EsmailELBoBDev2** [comment]
weird, that look means you blocked JS, wait i will add nojs tags & let's see

**Comment by EsmailELBoBDev2** [comment]
done, added the noscript tags so try to see the website again & give me screen shot, thx :)
