### ISSUE TITLE
WebRTC IP fetch fails: Site breaks

### ISSUE THREAD

**Issue by RedSQL** [EsmailELBoBDev2/Whatismyip#3]
Hey dude, saw your site on the forum, decided to try it out and it didn't work, I narrowed down the issue to WebRTC IP fetch failing if WebRTC is disabled in browser.

Should be fixed in #2 which fixes WebRTC fetch and adds a new IP fetch via HTTP which should be slightly more reliable.

**Comment by EsmailELBoBDev2** [comment]
first, thx a lot
second, ik i can do it via HTTP via third parties API but i not wanna do that thats why i made it inside webRTC because i not wanna it to connect to websites like website in HTTP code but thx i will take webRTC fixing code

**Comment by RedSQL** [comment]
Ah I see, that's understandable! 😄 Glad to help You! Closing the issue now as it no longer is producible.
